# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 14:29
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=25)),
                ('Location', models.URLField(max_length=50)),
                ('Address', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=25)),
                ('CreationDate', models.DateField()),
                ('Slug', models.SlugField()),
                ('Equipments', models.ManyToManyField(to='teams.Equipment')),
                ('GameFields', models.ManyToManyField(related_name='gameFields', to='teams.Field')),
                ('PracticeFields', models.ManyToManyField(related_name='practiceFields', to='teams.Field')),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JerseyColor', models.CharField(max_length=25)),
                ('JerseyColorRGB', colorful.fields.RGBColorField()),
                ('PantsColor', models.CharField(max_length=25)),
                ('PantsColorRGB', colorful.fields.RGBColorField()),
                ('HelmetColor', models.CharField(max_length=25)),
                ('HelmetColorRGB', colorful.fields.RGBColorField()),
                ('FaceMaskColor', models.CharField(max_length=25)),
                ('FaceMaskColorRGB', colorful.fields.RGBColorField()),
                ('SocksColor', models.CharField(max_length=25)),
                ('SocksColorRGB', colorful.fields.RGBColorField()),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='Field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Stadium'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='FirstUniform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstUniform', to='teams.Uniform'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='SecondUniform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondUniform', to='teams.Uniform'),
        ),
    ]
