# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:59
from __future__ import unicode_literals

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '__first__'),
        ('seasons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'.')),
            ],
        ),
        migrations.CreateModel(
            name='LogoSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Logo')),
                ('Season', models.ManyToManyField(to='seasons.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=35)),
                ('Region', models.CharField(max_length=25)),
                ('Map', models.URLField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StadiumSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameField', to='teams.Stadium')),
                ('PracticeField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practiceField', to='teams.Stadium')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Shortening', models.CharField(max_length=12)),
                ('History', models.CharField(blank=True, max_length=4000)),
                ('City', models.CharField(max_length=25)),
                ('CreationDate', models.DateField(blank=True)),
                ('Slug', models.SlugField()),
                ('WebSite', models.URLField(blank=True, max_length=50)),
                ('Twitter', models.CharField(blank=True, max_length=15)),
                ('Facebook', models.URLField(blank=True, max_length=50)),
                ('Instagram', models.CharField(blank=True, max_length=15)),
                ('Youtube', models.URLField(blank=True, max_length=50)),
                ('Active', models.BooleanField(default=True)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.Region')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JerseyColor', models.CharField(max_length=25)),
                ('JerseyColorRGB', colorfield.fields.ColorField(max_length=10)),
                ('PantsColor', models.CharField(max_length=25)),
                ('PantsColorRGB', colorfield.fields.ColorField(max_length=10)),
                ('HelmetColor', models.CharField(max_length=25)),
                ('HelmetColorRGB', colorfield.fields.ColorField(max_length=10)),
                ('FaceMaskColor', models.CharField(max_length=25)),
                ('FaceMaskColorRGB', colorfield.fields.ColorField(max_length=10)),
                ('SocksColor', models.CharField(max_length=25)),
                ('SocksColorRGB', colorfield.fields.ColorField(max_length=10)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_of', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='UniformSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstUniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstUniform', to='teams.Uniform')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.Season')),
                ('SecondUniform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondUniform', to='teams.Uniform')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_of', to='teams.Team')),
            ],
        ),
        migrations.AddField(
            model_name='stadiumseason',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadium_of', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='logoseason',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_of', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='logo',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
