# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 20:17
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LogoSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=35)),
                ('Region', models.CharField(max_length=25)),
                ('Map', models.URLField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StadiumSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameField', to='teams.Stadium')),
                ('PracticeField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practiceField', to='teams.Stadium')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Shortening', models.CharField(max_length=12)),
                ('History', models.CharField(blank=True, max_length=4000)),
                ('City', models.CharField(max_length=25)),
                ('CreationDate', models.DateField(blank=True)),
                ('Slug', models.SlugField()),
                ('WebSite', models.URLField(blank=True, max_length=50)),
                ('Twitter', models.CharField(blank=True, max_length=15)),
                ('Facebook', models.URLField(blank=True, max_length=50)),
                ('Instagram', models.CharField(blank=True, max_length=15)),
                ('Youtube', models.URLField(blank=True, max_length=50)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JerseyColor', models.CharField(max_length=25)),
                ('JerseyColorRGB', colorful.fields.RGBColorField()),
                ('PantsColor', models.CharField(max_length=25)),
                ('PantsColorRGB', colorful.fields.RGBColorField()),
                ('HelmetColor', models.CharField(max_length=25)),
                ('HelmetColorRGB', colorful.fields.RGBColorField()),
                ('FaceMaskColor', models.CharField(max_length=25)),
                ('FaceMaskColorRGB', colorful.fields.RGBColorField()),
                ('SocksColor', models.CharField(max_length=25)),
                ('SocksColorRGB', colorful.fields.RGBColorField()),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_of', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='UniformSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstUniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstUniform', to='teams.Uniform')),
                ('SecondUniform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondUniform', to='teams.Uniform')),
            ],
        ),
        migrations.AddField(
            model_name='stadiumseason',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadium_of', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='logo',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
