# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
        ('teams', '0002_auto_20161209_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoseason',
            name='Season',
        ),
        migrations.AddField(
            model_name='logoseason',
            name='Season',
            field=models.ManyToManyField(to='seasons.Season'),
        ),
    ]
