# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170519_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='logoseason',
            name='Logo',
        ),
        migrations.RemoveField(
            model_name='logoseason',
            name='Season',
        ),
        migrations.RemoveField(
            model_name='logoseason',
            name='Team',
        ),
        migrations.AddField(
            model_name='team',
            name='Logo',
            field=models.ImageField(default='default.png', upload_to='.'),
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='LogoSeason',
        ),
    ]
