# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20161120_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='SecondUniform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondUniform', to='teams.Uniform'),
        ),
    ]
