# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20170609_1730'),
        ('teams', '0002_auto_20170607_1728'),
    ]

    operations = [
    ]
