# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20161120_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='Location',
            new_name='Map',
        ),
        migrations.AlterField(
            model_name='stadium',
            name='City',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
