# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_merge_20170610_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Logo',
            field=models.ImageField(default=b'default.png', upload_to=b'.'),
        ),
    ]
