# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20170610_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Logo',
            field=models.ImageField(default='default.png', upload_to='.'),
        ),
    ]
