# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20161209_2033'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='Teams',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
