# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        ('teams', '0003_auto_20161209_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('BirthDate', models.DateField()),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('ZIPCode', models.CharField(max_length=7)),
                ('City', models.CharField(max_length=20)),
                ('Region', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('Mail', models.EmailField(max_length=254)),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Shortening', models.CharField(max_length=12)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.Player')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.Season')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.State')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
