# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('regions', '__first__'),
        ('players', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='LicenceSesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.LicenceDuration')),
            ],
        ),
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Active', models.BooleanField(default=True)),
                ('Shortening', models.CharField(max_length=4)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.Region')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Shortening', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ValidFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.LicenceSesion')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.States')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.AddField(
            model_name='licencesesion',
            name='Licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.LicenceType'),
        ),
    ]
