# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.LicenceSesion')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.LicenceType')),
            ],
        ),
        migrations.RenameModel(
            old_name='States',
            new_name='LicenceState',
        ),
        migrations.RemoveField(
            model_name='validfor',
            name='Duration',
        ),
        migrations.AddField(
            model_name='validfor',
            name='Licence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='licences.Licence'),
            preserve_default=False,
        ),
    ]
