# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0002_auto_20170519_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencesesion',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='licencesesion',
            name='Licence',
        ),
        migrations.AlterField(
            model_name='licence',
            name='Session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.LicenceDuration'),
        ),
        migrations.DeleteModel(
            name='LicenceSesion',
        ),
    ]
