# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0003_auto_20170519_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencetype',
            name='Active',
        ),
        migrations.AddField(
            model_name='licence',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
