# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0006_auto_20170526_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenceduration',
            name='MaximunBirthDate',
        ),
        migrations.RemoveField(
            model_name='licenceduration',
            name='MinimumBirthDate',
        ),
    ]
