# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0010_auto_20170526_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenceduration',
            old_name='MaximunBirthDate',
            new_name='MaximumBirthDate',
        ),
    ]
