# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0011_auto_20170526_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenceduration',
            name='MaximumBirthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='licenceduration',
            name='MinimumBirthDate',
            field=models.DateField(null=True),
        ),
    ]
