# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0012_auto_20170602_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='validfor',
            name='State',
        ),
        migrations.AlterField(
            model_name='licenceduration',
            name='MaximumBirthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licencehistory',
            name='Player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.ValidFor'),
        ),
        migrations.AddField(
            model_name='licencehistory',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.LicenceState'),
        ),
    ]
