# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0013_auto_20170602_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencetype',
            name='Gender',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Open')], default='O', max_length=1),
        ),
    ]
