# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionName', models.CharField(max_length=50)),
                ('ShortRegionName', models.CharField(max_length=3)),
                ('FederationName', models.CharField(max_length=50)),
                ('ShortFederationName', models.CharField(max_length=6)),
                ('Flag', models.ImageField(blank=True, upload_to=b'.')),
                ('FederationLogo', models.ImageField(blank=True, upload_to=b'.')),
                ('National', models.BooleanField(default=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
