# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-13 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionName', models.CharField(max_length=50)),
                ('ShortRegionName', models.CharField(max_length=3)),
                ('FederationName', models.CharField(max_length=50)),
                ('ShortFederationName', models.CharField(max_length=6)),
                ('Flag', models.ImageField(blank=True, upload_to='')),
                ('FederationLogo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
