# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='FederationLogo',
            field=models.ImageField(blank=True, upload_to='.'),
        ),
        migrations.AlterField(
            model_name='region',
            name='Flag',
            field=models.ImageField(blank=True, upload_to='.'),
        ),
    ]
