# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20170519_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='National',
            field=models.BooleanField(default=False),
        ),
    ]
