# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20170602_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='ShortFederationName',
            field=models.CharField(max_length=8),
        ),
    ]
