# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_auto_20170609_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='FederationLogo',
            field=models.ImageField(default='default.png', upload_to='.'),
        ),
    ]
