# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edition', models.CharField(max_length=10)),
                ('Years', models.CharField(max_length=9)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('MinimumBirthDate', models.DateField()),
                ('MaximumBirthDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CompetitionDuration',
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='Shortening',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='Name',
            field=models.CharField(max_length=45),
        ),
        migrations.AddField(
            model_name='competition',
            name='Condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.CompetitionConditions'),
        ),
        migrations.AddField(
            model_name='competition',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.CompetitionType'),
        ),
    ]
