# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20170526_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='Condition',
            new_name='Conditions',
        ),
    ]
