# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0014_licencetype_gender'),
        ('competitions', '0005_auto_20170706_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='Licences',
            field=models.ManyToManyField(to='licences.Licence'),
        ),
    ]
