# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_licences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionconditions',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
