# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20170706_1354'),
        ('licences', '0014_licencetype_gender'),
        ('regions', '0005_auto_20170609_1735'),
        ('competitions', '0008_auto_20170707_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edition', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='Conditions',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='Licences',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='Teams',
        ),
        migrations.RemoveField(
            model_name='competitionconditions',
            name='Edition',
        ),
        migrations.AlterUniqueTogether(
            name='competitiontype',
            unique_together=set([('Shortening', 'Region')]),
        ),
        migrations.AddField(
            model_name='edition',
            name='Competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition'),
        ),
        migrations.AddField(
            model_name='edition',
            name='Conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.CompetitionConditions'),
        ),
        migrations.AddField(
            model_name='edition',
            name='Licences',
            field=models.ManyToManyField(to='licences.Licence'),
        ),
        migrations.AddField(
            model_name='edition',
            name='Teams',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
