# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20170707_1705'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together=set([('Edition', 'Competition')]),
        ),
    ]
