# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenceid',
            name='Player',
        ),
        migrations.AddField(
            model_name='player',
            name='LicenceId',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='Photo',
            field=models.ImageField(upload_to='.'),
        ),
        migrations.DeleteModel(
            name='LicenceId',
        ),
    ]
