# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20170519_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Gender',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
